// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBemdaTkrnfPtgcPEboyLWj8SvM0vuQHEQ',
    appId: '1:1097288100578:web:f1b80eb5006e51bff3ccbb',
    messagingSenderId: '1097288100578',
    projectId: 'labsense-ai',
    authDomain: 'labsense-ai.firebaseapp.com',
    storageBucket: 'labsense-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNa1pJEp0-8XRIei9s9i57N2hHt_3P-pQ',
    appId: '1:1097288100578:android:c8f4f6ab7b95b4cef3ccbb',
    messagingSenderId: '1097288100578',
    projectId: 'labsense-ai',
    storageBucket: 'labsense-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgFK4EGGV0AIxSqrLO_u7MlzX95sW2kZ4',
    appId: '1:1097288100578:ios:869f37c7ff214afef3ccbb',
    messagingSenderId: '1097288100578',
    projectId: 'labsense-ai',
    storageBucket: 'labsense-ai.firebasestorage.app',
    iosBundleId: 'com.example.labsenseAi',
  );
}
